# -*- coding: utf-8 -*-
"""DiabetesReadmission.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Tdz-d3Hrw2nZQS_Oo6aY2bjERmQB2Qs
"""

import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

data = pd.read_csv("data/diabetic_data.csv")
data

data.head()

data.tail()

data.info()

data.isnull().sum()

data['max_glu_serum'].unique()

data['A1Cresult'].unique()

glu_mapping = {'Norm': 0, '>200': 1, '>300': 2}
a1c_mapping = {'Norm': 0, '>7': 1, '>8': 2}

data['max_glu_serum'] = data['max_glu_serum'].map(glu_mapping).fillna(-1).astype(int)
data['A1Cresult'] = data['A1Cresult'].map(a1c_mapping).fillna(-1).astype(int)

data['A1Cresult'].unique()

data['max_glu_serum'].unique()

data.isnull().sum()

for i in data.columns:
    if data[i].dtype == object:
        print(i, data[i][data[i] == '?'].count())

data = data.drop(['weight','payer_code','medical_specialty'], axis = 1)

data = data.drop(['encounter_id'], axis = 1)

data.describe()

data['patient_nbr'].nunique()

data.drop(['patient_nbr'], axis=1,inplace=True)

data['race'].value_counts()

data['race'] = data['race'].replace("?", np.nan)

data['race'].unique()

data["race"] = data["race"].fillna(data["race"].mode()[0])

data['race'].value_counts()

data['gender'].value_counts()

data['gender'] = data['gender'].replace("Unknown/Invalid", np.nan)
data['gender'].dropna(inplace=True)

data['gender'].value_counts()

data['gender'].unique()

data["gender"] = data["gender"].fillna(data["gender"].mode()[0])

data['gender'].value_counts()

data.replace('?', np.nan, inplace=True)

data.isnull().sum()

data['age'].unique()

data["age"] = data["age"].replace({
    "[0-10)": 5, "[10-20)": 15, "[20-30)": 25, "[30-40)": 35, "[40-50)": 45,
    "[50-60)": 55, "[60-70)": 65, "[70-80)": 75, "[80-90)": 85, "[90-100)": 95
})

data['age'].unique()

data['age'].value_counts()

data['admission_type_id'].value_counts()

data['time_in_hospital'].value_counts(sort=False)

print('The number of medications range from a minimum of',
      data.num_medications.min(),
      'to maximum of',
      data.num_medications.max())

data.head()

data.shape

data.info()

data['readmitted'].value_counts()

data['readmitted'].unique()

data['readmitted'] = data['readmitted'].replace({'NO' : 0, '<30' : 1, '>30' : 0})

data['readmitted'].value_counts()

data['A1Cresult'].unique()

data['A1Cresult'].value_counts()

data['A1Cresult'] = data['A1Cresult'].replace({'None':0, "Norm":1, ">7" :2, ">8" : 2})

data.columns

data.drop(['admission_type_id',
       'discharge_disposition_id', 'admission_source_id',
       'diag_1',
       'diag_2', 'diag_3'], axis=1, inplace=True)

data['gender'] = data['gender'].replace({'Female':0,'Male':1})

data['change'].value_counts()

data['change'] = data['change'].replace({'No':0,'Ch':1})

data['diabetesMed'].value_counts()

data['diabetesMed'] = data['diabetesMed'].replace({'Yes':1,'No':0})

data['diabetesMed'].value_counts()

data.columns

drug = list(data.iloc[:,16:36].columns)
drug

import seaborn as sns
import matplotlib.pyplot as plt

for i in drug:
  print(i)
  print(sns.countplot(data[i]))
  plt.show()

data.columns

data.isnull().sum()

data['readmitted'].value_counts()

data['A1Cresult'].unique()

data['A1Cresult'].value_counts()

data['gender'].value_counts()

data['diabetesMed'].value_counts()

data.columns

data.info()

medication_columns = [
    "metformin", "repaglinide", "nateglinide", "chlorpropamide", "glimepiride",
    "acetohexamide", "glipizide", "glyburide", "tolbutamide", "pioglitazone",
    "rosiglitazone", "acarbose", "miglitol", "troglitazone", "tolazamide",
    "examide", "citoglipton", "glyburide-metformin",
    "glipizide-metformin", "glimepiride-pioglitazone",
    "metformin-rosiglitazone", "metformin-pioglitazone"
]

data.drop(columns=medication_columns, inplace=True)

data.info()

data['change'].unique()

data['change'].value_counts()

data.head()

data['race'].value_counts()

data['race'] = data['race'].replace({'Caucasian' : 0, 'AfricanAmerican' : 1, 'Hispanic' : 2, 'Other' : 3, 'Asian' : 4})

data['race'].value_counts()

data['insulin'].value_counts()

data['insulin'] = data['insulin'].replace({'NO' : 0, 'Steady' : 1, 'Down' : 2, 'Up' : 3})
data['insulin'].value_counts()

data['insulin'] = data['insulin'].replace({'No' : 0})
data['insulin'].value_counts()

data.info()

plt.figure(figsize=(5, 8))
sns.countplot(x=data['readmitted'])
plt.show()

from sklearn.utils import resample

# Separate majority and minority classes
majority = data[data['readmitted'] == 0]
minority = data[data['readmitted'] == 1]

# Upsample minority class
minority_upsampled = resample(minority,
                               replace=True,         # Sample with replacement
                               n_samples=len(majority), # Match majority class size
                               random_state=42)      # Reproducibility

# Combine majority class with upsampled minority class
balanced_data = pd.concat([majority, minority_upsampled])

# Shuffle the data (optional but recommended)
balanced_data = balanced_data.sample(frac=1, random_state=42).reset_index(drop=True)

# Check new class distribution
print(balanced_data['readmitted'].value_counts())

plt.figure(figsize=(5, 8))
sns.countplot(x=balanced_data['readmitted'])
plt.show()

balanced_data

plt.figure(figsize=(5, 8))
sns.countplot(x=balanced_data['age'])
plt.show()

balanced_data['readmitted'].value_counts()

balanced_data.columns

balanced_data['insulin'].value_counts()

balanced_data.corr()

plt.figure(figsize=(15,10))
sns.heatmap(balanced_data.corr(), annot = True)

balanced_data['total_procedures'] = balanced_data['num_lab_procedures'] + balanced_data['num_procedures']

balanced_data['outpatient_to_inpatient_ratio'] = balanced_data['number_outpatient'] / balanced_data['number_inpatient'].replace(0, np.nan)

columns_to_drop = [
    'num_lab_procedures',
    'num_procedures',
    'number_outpatient',
    'number_inpatient'
]
balanced_data = balanced_data.drop(columns=columns_to_drop)

balanced_data

balanced_data.isnull().sum()

balanced_data['outpatient_to_inpatient_ratio'] = balanced_data['outpatient_to_inpatient_ratio'].fillna(0)

column_mean = balanced_data['outpatient_to_inpatient_ratio'].mean()

balanced_data['outpatient_to_inpatient_ratio'] = balanced_data['outpatient_to_inpatient_ratio'].replace(0, column_mean)

balanced_data.isnull().sum()

balanced_data

balanced_data['medication'] = balanced_data['num_medications'] + balanced_data['number_diagnoses']

columns_to_drop = [
    'number_diagnoses',
    'num_medications'
]
balanced_data = balanced_data.drop(columns=columns_to_drop)

balanced_data

balanced_data.corr()

x = balanced_data.drop('readmitted', axis=1)
y = balanced_data['readmitted']
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42, stratify=y)

print(f"Features (X) shape: {x.shape}")
print(f"Target (y) shape: {y.shape}")

from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)

rf_model.fit(x_train, y_train)

print("Random Forest model trained successfully.")

y_pred = rf_model.predict(x_test)

import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV, KFold, cross_val_score
from sklearn.preprocessing import PowerTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    confusion_matrix,
    classification_report,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)
from sklearn.pipeline import Pipeline
from warnings import filterwarnings

filterwarnings('ignore')

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PowerTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, precision_score, recall_score, f1_score, roc_auc_score


pipe = Pipeline([
    ("pt", PowerTransformer()),
    ("rf", RandomForestClassifier(random_state=10, class_weight="balanced"))
])


pipe.fit(x_train, y_train)


print("Training Accuracy")
print(pipe.score(x_train, y_train))


print("Testing Accuracy")
te_acc = pipe.score(x_test, y_test)
print(te_acc)


score = cross_val_score(estimator=pipe, X=x_train, y=y_train, scoring="accuracy", cv=5)
print("Cross Validation Score:", np.mean(score))


pred = pipe.predict(x_test)
predx = pipe.predict(x_train)


print("Confusion Matrix (Test Set):")
print(confusion_matrix(y_test, pred))

print("Classification Report (Test Set):")
print(classification_report(y_test, pred))

import joblib


joblib.dump(pipe, "model_01.pkl")
print("Model saved successfully!")

from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression

xgb_pipe = Pipeline([
    ("pt", PowerTransformer()),
    ("xgb", XGBClassifier(random_state=10, use_label_encoder=False, eval_metric='logloss'))
])

xgb_pipe.fit(x_train, y_train)

print("\nXGBoost Training Accuracy:", xgb_pipe.score(x_train, y_train))
print("XGBoost Testing Accuracy:", xgb_pipe.score(x_test, y_test))
xgb_cv_score = cross_val_score(xgb_pipe, x_train, y_train, cv=5, scoring="accuracy")
print("XGBoost Cross Validation Score:", np.mean(xgb_cv_score))

xgb_pred = xgb_pipe.predict(x_test)
print("XGBoost Confusion Matrix:")
print(confusion_matrix(y_test, xgb_pred))
print("XGBoost Classification Report:")
print(classification_report(y_test, xgb_pred))

joblib.dump(xgb_pipe, "xgb_model.pkl")
print("XGBoost model saved successfully!")

lr_pipe = Pipeline([
    ("pt", PowerTransformer()),
    ("lr", LogisticRegression(random_state=10, class_weight="balanced", max_iter=1000))
])

lr_pipe.fit(x_train, y_train)

print("\nLogistic Regression Training Accuracy:", lr_pipe.score(x_train, y_train))
print("Logistic Regression Testing Accuracy:", lr_pipe.score(x_test, y_test))
lr_cv_score = cross_val_score(lr_pipe, x_train, y_train, cv=5, scoring="accuracy")
print("Logistic Regression Cross Validation Score:", np.mean(lr_cv_score))

lr_pred = lr_pipe.predict(x_test)
print("Logistic Regression Confusion Matrix:")
print(confusion_matrix(y_test, lr_pred))
print("Logistic Regression Classification Report:")
print(classification_report(y_test, lr_pred))

joblib.dump(lr_pipe, "logistic_model.pkl")
print("Logistic Regression model saved successfully!")



# Collect predictions
models = {
    "Random Forest": pipe,
    "XGBoost": xgb_pipe,
    "Logistic Regression": lr_pipe
}

# Initialize metric lists
model_names = []
accuracy_list = []
precision_list = []
recall_list = []
f1_list = []
roc_auc_list = []

for name, model in models.items():
    y_pred = model.predict(x_test)
    model_names.append(name)
    accuracy_list.append(accuracy_score(y_test, y_pred))
    precision_list.append(precision_score(y_test, y_pred))
    recall_list.append(recall_score(y_test, y_pred))
    f1_list.append(f1_score(y_test, y_pred))
    roc_auc_list.append(roc_auc_score(y_test, y_pred))

# Create a DataFrame with all results
results_df = pd.DataFrame({
    "Model": model_names,
    "Accuracy": accuracy_list,
    "Precision": precision_list,
    "Recall": recall_list,
    "F1 Score": f1_list,
    "ROC AUC": roc_auc_list
})

# Display the table sorted by F1 Score (optional)
results_df = results_df.sort_values(by="F1 Score", ascending=False).reset_index(drop=True)

print("\nModel Comparison Table:")
print(results_df)
